#!/bin/bash 

MAIN_CLASS="PartAdjacentList"
if [ -z "$HADOOP_HOME" ]; then
    export HADOOP=`which hadoop`
else
    export HADOOP="$HADOOP_HOME/bin/hadoop"
fi

basedir=`dirname "${BASH_SOURCE-$0}"`
jardir="/home/dev/handongqing/libjars"
libdir="/home/dev/handongqing/libjars"
JAR=$(ls $jardir/babel*.jar)
dependencies=$(ls $libdir/*.jar | tr '\n' :)
export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$dependencies
export LIBJARS=`echo ${dependencies} | sed s/:/,/g`
export JAVA_HOME=/usr/java/jdk
echo "run command : $HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} reducer_number input_path output_path "

$HADOOP fs -rm -r -f /user/handongqing/prod_part_adjacent/*
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0000* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_000
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0010* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_001
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0020* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_002
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0030* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_003
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0040* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_004
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0050* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_005
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0060* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_006
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0070* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_007
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0080* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_008
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0090* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_009
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0001* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_010
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0011* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_011
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0021* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_012
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0031* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_013
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0041* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_014
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0051* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_015
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0061* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_016
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0071* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_017
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0081* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_018
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0091* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_019
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0002* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_020
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0012* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_021
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0022* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_022
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0032* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_023
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0042* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_024
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0052* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_025
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0062* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_026
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0072* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_027
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0082* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_028
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0092* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_029
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0003* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_030
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0013* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_031
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0023* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_032
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0033* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_033
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0043* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_034
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0053* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_035
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0063* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_036
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0073* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_037
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0083* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_038
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0093* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_039
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0004* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_040
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0014* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_041
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0024* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_042
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0034* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_043
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0044* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_044
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0054* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_045
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0064* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_046
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0074* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_047
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0084* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_048
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0094* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_049
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0005* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_050
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0015* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_051
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0025* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_052
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0035* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_053
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0045* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_054
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0055* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_055
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0065* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_056
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0075* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_057
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0085* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_058
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0095* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_059
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0006* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_060
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0016* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_061
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0026* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_062
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0036* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_063
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0046* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_064
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0056* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_065
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0066* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_066
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0076* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_067
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0086* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_068
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0096* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_069
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0007* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_070
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0017* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_071
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0027* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_072
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0037* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_073
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0047* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_074
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0057* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_075
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0067* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_076
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0077* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_077
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0087* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_078
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0097* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_079
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0008* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_080
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0018* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_081
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0028* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_082
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0038* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_083
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0048* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_084
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0058* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_085
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0068* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_086
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0078* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_087
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0088* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_088
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0098* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_089
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0009* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_090
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0019* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_091
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0029* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_092
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0039* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_093
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0049* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_094
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0059* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_095
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0069* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_096
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0079* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_097
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0089* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_098
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0099* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_099
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0100* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_100
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0110* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_101
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0120* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_102
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0130* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_103
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0140* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_104
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0150* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_105
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0160* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_106
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0170* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_107
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0180* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_108
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0190* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_109
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0101* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_110
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0111* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_111
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0121* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_112
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0131* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_113
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0141* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_114
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0151* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_115
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0161* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_116
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0171* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_117
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0181* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_118
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0191* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_119
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0102* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_120
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0112* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_121
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0122* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_122
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0132* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_123
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0142* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_124
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0152* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_125
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0162* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_126
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0172* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_127
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0182* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_128
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0192* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_129
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0103* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_130
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0113* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_131
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0123* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_132
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0133* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_133
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0143* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_134
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0153* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_135
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0163* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_136
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0173* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_137
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0183* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_138
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0193* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_139
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0104* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_140
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0114* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_141
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0124* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_142
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0134* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_143
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0144* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_144
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0154* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_145
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0164* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_146
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0174* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_147
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0184* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_148
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0194* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_149
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0105* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_150
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0115* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_151
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0125* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_152
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0135* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_153
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0145* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_154
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0155* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_155
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0165* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_156
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0175* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_157
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0185* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_158
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0195* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_159
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0106* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_160
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0116* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_161
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0126* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_162
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0136* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_163
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0146* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_164
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0156* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_165
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0166* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_166
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0176* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_167
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0186* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_168
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0196* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_169
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0107* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_170
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0117* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_171
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0127* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_172
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0137* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_173
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0147* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_174
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0157* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_175
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0167* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_176
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0177* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_177
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0187* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_178
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0197* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_179
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0108* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_180
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0118* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_181
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0128* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_182
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0138* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_183
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0148* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_184
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0158* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_185
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0168* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_186
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0178* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_187
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0188* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_188
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0198* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_189
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0109* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_190
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0119* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_191
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0129* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_192
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0139* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_193
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0149* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_194
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0159* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_195
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0169* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_196
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0179* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_197
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0189* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_198
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0199* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_199
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0200* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_200
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0210* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_201
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0220* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_202
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0230* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_203
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0240* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_204
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0250* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_205
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0260* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_206
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0270* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_207
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0280* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_208
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0290* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_209
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0201* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_210
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0211* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_211
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0221* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_212
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0231* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_213
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0241* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_214
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0251* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_215
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0261* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_216
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0271* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_217
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0281* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_218
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0291* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_219
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0202* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_220
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0212* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_221
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0222* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_222
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0232* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_223
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0242* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_224
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0252* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_225
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0262* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_226
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0272* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_227
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0282* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_228
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0292* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_229
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0203* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_230
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0213* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_231
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0223* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_232
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0233* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_233
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0243* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_234
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0253* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_235
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0263* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_236
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0273* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_237
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0283* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_238
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0293* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_239
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0204* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_240
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0214* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_241
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0224* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_242
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0234* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_243
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0244* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_244
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0254* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_245
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0264* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_246
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0274* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_247
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0284* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_248
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0294* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_249
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0205* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_250
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0215* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_251
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0225* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_252
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0235* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_253
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0245* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_254
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0255* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_255
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0265* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_256
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0275* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_257
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0285* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_258
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0295* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_259
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0206* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_260
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0216* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_261
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0226* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_262
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0236* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_263
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0246* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_264
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0256* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_265
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0266* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_266
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0276* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_267
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0286* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_268
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0296* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_269
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0207* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_270
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0217* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_271
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0227* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_272
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0237* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_273
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0247* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_274
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0257* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_275
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0267* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_276
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0277* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_277
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0287* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_278
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0297* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_279
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0208* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_280
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0218* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_281
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0228* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_282
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0238* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_283
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0248* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_284
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0258* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_285
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0268* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_286
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0278* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_287
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0288* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_288
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0298* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_289
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0209* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_290
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0219* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_291
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0229* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_292
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0239* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_293
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0249* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_294
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0259* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_295
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0269* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_296
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0279* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_297
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0289* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_298
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0299* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_299
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0300* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_300
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0310* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_301
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0320* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_302
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0330* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_303
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0340* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_304
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0350* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_305
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0360* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_306
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0370* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_307
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0380* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_308
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0390* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_309
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0301* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_310
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0311* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_311
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0321* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_312
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0331* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_313
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0341* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_314
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0351* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_315
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0361* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_316
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0371* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_317
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0381* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_318
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0391* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_319
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0302* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_320
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0312* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_321
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0322* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_322
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0332* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_323
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0342* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_324
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0352* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_325
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0362* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_326
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0372* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_327
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0382* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_328
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0392* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_329
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0303* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_330
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0313* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_331
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0323* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_332
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0333* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_333
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0343* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_334
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0353* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_335
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0363* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_336
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0373* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_337
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0383* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_338
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0393* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_339
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0304* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_340
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0314* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_341
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0324* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_342
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0334* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_343
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0344* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_344
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0354* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_345
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0364* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_346
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0374* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_347
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0384* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_348
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0394* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_349
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0305* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_350
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0315* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_351
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0325* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_352
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0335* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_353
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0345* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_354
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0355* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_355
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0365* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_356
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0375* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_357
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0385* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_358
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0395* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_359
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0306* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_360
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0316* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_361
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0326* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_362
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0336* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_363
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0346* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_364
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0356* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_365
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0366* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_366
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0376* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_367
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0386* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_368
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0396* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_369
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0307* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_370
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0317* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_371
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0327* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_372
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0337* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_373
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0347* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_374
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0357* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_375
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0367* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_376
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0377* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_377
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0387* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_378
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0397* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_379
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0308* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_380
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0318* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_381
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0328* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_382
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0338* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_383
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0348* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_384
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0358* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_385
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0368* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_386
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0378* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_387
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0388* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_388
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0398* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_389
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0309* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_390
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0319* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_391
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0329* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_392
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0339* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_393
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0349* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_394
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0359* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_395
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0369* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_396
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0379* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_397
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0389* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_398
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0399* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_399
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0400* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_400
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0410* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_401
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0420* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_402
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0430* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_403
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0440* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_404
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0450* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_405
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0460* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_406
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0470* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_407
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0480* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_408
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0490* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_409
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0401* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_410
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0411* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_411
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0421* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_412
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0431* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_413
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0441* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_414
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0451* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_415
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0461* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_416
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0471* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_417
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0481* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_418
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0491* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_419
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0402* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_420
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0412* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_421
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0422* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_422
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0432* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_423
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0442* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_424
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0452* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_425
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0462* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_426
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0472* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_427
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0482* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_428
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0492* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_429
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0403* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_430
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0413* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_431
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0423* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_432
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0433* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_433
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0443* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_434
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0453* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_435
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0463* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_436
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0473* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_437
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0483* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_438
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0493* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_439
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0404* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_440
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0414* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_441
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0424* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_442
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0434* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_443
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0444* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_444
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0454* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_445
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0464* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_446
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0474* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_447
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0484* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_448
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0494* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_449
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0405* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_450
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0415* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_451
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0425* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_452
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0435* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_453
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0445* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_454
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0455* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_455
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0465* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_456
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0475* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_457
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0485* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_458
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0495* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_459
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0406* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_460
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0416* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_461
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0426* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_462
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0436* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_463
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0446* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_464
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0456* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_465
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0466* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_466
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0476* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_467
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0486* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_468
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0496* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_469
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0407* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_470
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0417* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_471
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0427* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_472
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0437* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_473
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0447* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_474
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0457* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_475
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0467* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_476
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0477* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_477
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0487* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_478
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0497* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_479
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0408* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_480
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0418* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_481
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0428* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_482
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0438* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_483
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0448* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_484
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0458* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_485
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0468* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_486
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0478* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_487
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0488* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_488
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0498* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_489
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0409* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_490
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0419* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_491
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0429* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_492
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0439* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_493
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0449* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_494
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0459* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_495
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0469* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_496
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0479* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_497
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0489* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_498
$HADOOP jar ${JAR} $MAIN_CLASS -libjars ${LIBJARS} 64 /user/handongqing/prod_deduplicate_result/part-r-0499* /user/handongqing/prod_part_adjacent/prod_part_adjacent_list_499

if [ $? -ne 0 ]
then
    echo "run hive sql failed !"
    exit 255
fi

 
